### ISSUE TITLE
Server Crash -v1.12-2.3 (Class not found -ClientProxy)

### ISSUE THREAD

**Issue by JoelZBub** [LewisMcReu/LightAir#3] opened 2017-12-31 17:21 UTC
Forge Version : any
MC version : 1.12.2
Java: 1.8.0_72

Server loads without crash using LightAir version 2.2. 
Server crashes using version 2.3 with the following exception:
`Caught exception from LightAir (lightair)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.lewismcreu.lightair.ClientProxy`

Crashlog: [https://pastebin.com/hiMNsVTw](url)

**Comment by LewisMcReu** [comment] 2018-02-06 15:12
Duplicate of #2

**Closed by LewisMcReu** 2018-02-06 15:12 UTC
